first commit - issues with imports and packages
companieshouse/psc-statement-data-api pull request #91
Opened 2024-07-09 12:10 UTC by maddytjCH

- Added DataMapHolder
- Added MessageLoggingAspect (problems with imports)
- ApplicationConfig can't find the converter package (it's there - untouched)
- Issues with Maven compiler: "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project psc-statement-data-api: Fatal error compiling: error: invalid target release: 21 -> [Help 1]"

2024-07-16 07:46 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-17 18:32 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-18 10:58 UTC, lbedrosyanCH requested changes

2024-07-18 10:58 UTC, lbedrosyanCH commented on src/main/java/uk/gov/companieshouse/pscstatementdataapi/controller/PscStatementController.java
> +        logger.info(String.format("Processing psc statement data for company number %s and statement_id %s",
I think it would be better to use logger.infoContext(), also supplying the contextId

2024-07-18 12:01 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-18 14:58 UTC, merged

2024-07-18 14:59 UTC, ch-code-analysis commented
CI: Security warnings found!